version: '3'
services:
  web:
    image: webdevops/php-apache-dev:8.1
    container_name: web
    restart: always
    user: application
    environment:
      - WEB_ALIAS_DOMAIN=docker.m2ce.local
      - WEB_DOCUMENT_ROOT=/app/pub
      - PHP_DATE_TIMEZONE=EST
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=1024M
    volumes:
      - /app/root:/app:cached
    ports:
      - "80:80"
      - "443:443"
      - "32823:22"
    links:
      - mysql
  mysql:
    image: mariadb:10.4
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ub9M3FnHb6R3ykbk
      - MYSQL_DATABASE=magento
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - MYSQL_ROOT_PASSWORD=ub9M3FnHb6R3ykbk
      - PMA_USER=root
      - PMA_PASSWORD=ub9M3FnHb6R3ykbk
    ports:
      - "8080:80"
    links:
      - mysql:db
    depends_on:
      - mysql
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  db-data:
    external: false
  es-data:
    driver: local
    external: false
